package handler

import "github.com/gin-gonic/gin"

func BookingRequest(c *gin.Context) {

	/*BookingId  // Generated by code
	UserId       // from post request
	BookingDate  // from the post request
	RideDate     // from the post request
	SourceAddress // from the post request
	SourceCity    // from the post request
	SourceState   // from the post request
	SourcePincode // from the post request
	SourceLongitude // from the post request
	SourceLatitude  // from the post request
	DestinationLatitude // from the post request
	DestinationLongitude // from the post request
	DestinationAddress // from the post request
	DestinationState // from the post request
	DestinationPincode // from the post request
	BookingTime    // Current time from go code
	RideTime      //from the post request
	SlotTime     //from the post request
	SlotNumber   //from the post request
	Distance     //calculated from background service in GO
	Amount     // calculate in Go code
	Status    // booking status code
	CreatedAt
	UpdatedAt
	*/

}
